export const Comodos = {
  AreaDeServico: 1,
  Cozinha: 2,
  SalaDeEstar: 3,
  SalaDeJantar: 4,
  Suite: 5,
  Varanda: 6,
  WcSocial: 7,
  WcDeServico: 8,
  Despensa: 9,
  QuartoDeServico: 10,
  SalaDeVisita: 11,
  BanheiroSocial: 12,
  Lavabo: 13,
  Escritorio: 14,
  HomeOffice: 15,
  Closet: 16,
  Hall: 17,
  SalaDeTv: 18,
  Terraco: 19,
};

export const Infraestrutura = {
  Garagem: 1,
  Lavanderia: 2,
  JardimInterno: 3,
  JardimExterno: 4,
  Piscina: 5,
  Playground: 6,
  Portaria24h: 7,
  SalaoDeFestas: 8,
  SistemaDeSeguranca: 9,
  Churrasqueira: 10,
  Elevador: 11,
  Sauna: 12,
  QuadraPoliesportiva: 13,
  Academia: 14,
  CampoDeFutebol: 15,
  Bicicletario: 16,
  AreaDeLazer: 17,
  CentralDeGas: 18,
  PortaoEletronico: 19,
  Gerador: 20,
  Interfone: 21,
  Guarita: 22,
  Monitoramento: 23,
  CFTV: 24,
  Brinquedoteca: 25,
  SalaoDeJogos: 26,
  Spa: 27,
  Coworking: 28,
  PetPlace: 29,
  CarWash: 30,
  MiniMercado: 31,
  EstacionamentoVisitantes: 32,
};

export const Piso = {
  Porcelanato: 1,
  Ceramica: 2,
  Granito: 3,
  Laminado: 4,
  Madeira: 5,
  Vinilico: 6,
  Carpete: 7,
  Ardosia: 8,
  Marmore: 9,
  Taco: 10,
};

export const Posicao = {
  Nascente: 1,
  VistaParaOMar: 2,
  BeiraMar: 3,
  Poente: 4,
  FrenteParaOMar: 5,
  Norte: 6,
  Sul: 7,
  Leste: 8,
  Oeste: 9,
};

export const Proximidades = {
  BaresERestaurantes: 1,
  Escola: 2,
  Faculdade: 3,
  Farmacia: 4,
  Hospital: 5,
  Padaria: 6,
  PetShop: 7,
  ShoppingCenter: 8,
  Supermercado: 9,
  Banco: 10,
  Shopping: 11,
  Praia: 12,
  Parque: 13,
  Metro: 14,
  EstacaoDeMetro: 15,
  Estacao: 16,
  PontoDeOnibus: 17,
  Terminal: 18,
  Igreja: 19,
  Feira: 20,
  Mercado: 21,
  PostoDeGasolina: 22,
  Delegacia: 23,
  Correios: 24,
  Loterica: 25,
  Universidade: 26,
  Creche: 27,
};